name: sample-nodejs-kafka
services:
- name: producer
  source_dir: producer
  github:
    repo: blesswinsamuel/sample-nodejs-kafka
    branch: main
- name: consumer
  source_dir: consumer
  github:
    repo: blesswinsamuel/sample-nodejs-kafka
    branch: main
